version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run test:ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist s3://$OUTPUT_BUCKET
