name: Deploy

on:
  push:
    branches: ['master']

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Retrieve version
        run: |
          echo "NODE_VERSION=$(cat .nvmrc | sed /\*/x/g)" >> $GITHUB_OUTPUT
        id: node_version
      - name: Setup Node.js ${{ steps.get-node-version.outputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Deploy
        run: npx -p @angular/cli ng deploy --name "Thegajout" --no-silent
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_PAGES }}

